###
GET http://localhost:3001/api/notes/


###
POST http://localhost:3001/api/notes/
Content-Type: application/json

{
    "content": "keep the db stuff in a separete module in a models folder",
    "important": true
}